---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Set timezone
  timezone:
    name: "{{ timezone | default('Europe/Kyiv') }}"

- name: Install base packages
  apt:
    name:
      - curl
      - git
      - htop
      - unzip
      - net-tools
      - vim
      - tmux
      - lsb-release
      - ca-certificates
      - software-properties-common
      - ufw
    state: present

- name: Enable UFW firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow SSH through firewall
  ufw:
    rule: allow
    name: OpenSSH
