version: '3'

env:
  ANSIBLE_CONFIG: ansible/ansible.cfg
  ANSIBLE_HOST: 192.168.0.123 # paste host here
  ANSIBLE_USER: ihord # paste user here
  TIMEZONE: Europe/Kyiv
  USE_SWAP: true
  HOSTNAME: raspberrypi # paste hostname here
  SSD_MOUNT_POINT: /mnt/ssd
  SSH_KEY: raspberry


tasks:
  setup:
    desc: Run Ansible Playbook to configure Raspberry Pi
    cmds:
      - >
        ansible-playbook ansible/site.yml
        -e ansible_host={{.ANSIBLE_HOST}}
        -e ansible_user={{.ANSIBLE_USER}}
        -e HOSTNAME={{.HOSTNAME}}
        -e SSD_MOUNT_POINT={{.SSD_MOUNT_POINT}}
        -e TIMEZONE={{.TIMEZONE}}
        -e USE_SWAP={{.USE_SWAP}}

  ping:
    desc: Check Ansible connectivity
    cmds:
      - >
        ansible -i ansible/inventory/hosts all -m ping
        -e ansible_host={{.ANSIBLE_HOST}}
        -e ansible_user={{.ANSIBLE_USER}}

  ssh:
    desc: SSH into Raspberry Pi
    cmds:
      - ssh {{.ANSIBLE_USER}}@{{.ANSIBLE_HOST}}

  logs:
    desc: Tail system logs (ISO format, all units)
    cmds:
      - ssh -i {{.SSH_KEY}} {{.ANSIBLE_USER}}@{{.ANSIBLE_HOST}} \
        "journalctl -f -n 100 --output=short-iso --no-pager"

  logs:compact:
    desc: Tail system logs (compact, message-only)
    cmds:
      - ssh -i {{.SSH_KEY}} {{.ANSIBLE_USER}}@{{.ANSIBLE_HOST}} \
        "journalctl -f -n 100 --output=cat --no-pager"

  logs:pretty:
    desc: Tail system logs (pretty JSON)
    cmds:
      - ssh -i {{.SSH_KEY}} {{.ANSIBLE_USER}}@{{.ANSIBLE_HOST}} \
        "journalctl -f -n 100 --output=json-pretty --no-pager"

  logs:docker:
    desc: Tail logs from Docker service only
    cmds:
      - ssh -i {{.SSH_KEY}} {{.ANSIBLE_USER}}@{{.ANSIBLE_HOST}} \
        "journalctl -u docker.service -f -n 100 --output=short-iso --no-pager"

  logs:sshd:
    desc: Tail logs from SSHD (auth/login)
    cmds:
      - ssh -i {{.SSH_KEY}} {{.ANSIBLE_USER}}@{{.ANSIBLE_HOST}} \
        "journalctl -u ssh -f -n 100 --output=short-iso --no-pager"
